### ISSUE TITLE
master does not build on Windows

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [tsearle/script#3]
Scenario : 
- git clone repo
- mvn exec:java FAILS

Environment : 
- mvn -v
  Apache Maven 3.3.9 
  Maven home: C:\Maven
  Java version: 1.8.0_74, vendor: Oracle Corporation
  Java home: C:\Program Files\Java\jdk1.8.0_74\jre
  Default locale: en_US, platform encoding: Cp1252
  OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

Here is output of the mvn exec:java :

```
> mvn exec:java
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.sipstacks.script:script:jar:0.6.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 47, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building script 0.6.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.3.2:java (default-cli) @ script ---
[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6.
[WARNING]
java.lang.ClassNotFoundException: com.sipstacks.script.CliInterpreter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.789 s
[INFO] Finished at: 2016-04-19T03:20:54-07:00
[INFO] Final Memory: 7M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java (default-cli) on project script: An exception occured while executing the Java class. com.sipstacks.script.CliInterpreter -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by tsearle** [comment]
run
mvn install

**Comment by ObjectIsAdvantag** [comment]
Tested : ok

doc updated needed for v0.6.3

To run, do : 

```
> mvn install
> mvn exec:java
```
